export const fakeAlbums = [
  {
    id: 1,
    title: "Rolling Rock",
    categories: ["Rock 'n' Roll"],
    description: "A classic rock 'n' roll album.",
    sold: false,
    price: 29.99,
  },
  {
    id: 2,
    title: "Bluesy Soul",
    categories: ["Blues", "Funk_Soul"],
    description: "An engaging blend of blues and soul.",
    sold: true,
    price: 19.99,
  },
  {
    id: 3,
    title: "Jazz sei la",
    categories: ["Jazz"],
    description: "A musical journey through the world of jazz.",
    sold: true,
    price: 24.99,
  },
  {
    id: 3,
    title: "Jazz lalalal",
    categories: ["Jazz"],
    description: "A musical journey through the world of jazz.",
    sold: true,
    price: 243.993,
  },
  {
    id: 4,
    title: "Folklore Chronicles",
    categories: ["Folk"],
    description: "An exciting collection of folk songs.",
    sold: false,
    price: 14.99,
  },
  {
    id: 5,
    title: "Reggae Roots",
    categories: ["Reggae"],
    description: "The deep roots of reggae.",
    sold: true,
    price: 22.99,
  },
  {
    id: 6,
    title: "Symphony Dreams",
    categories: ["Classical"],
    description: "A stunning collection of classical compositions.",
    sold: false,
    price: 32.99,
  },
  // Add more examples here...
];
